[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311']

[tool.isort]
profile = "black"
line_length = 88
known_third_party = ["flask", "django", "pytest", "requests"]
known_first_party = ["llm_lwr_crag"]
